/*15/03/2024*/

-- SELECIONA O DICIONÁRIO DE DADOS DO BANCO DE DADOS
USE INFORMATION_SCHEMA;

-- MOSTRA AS TABELAS PRESENTES DENTRO DO DICIONÁRIO DE DADOS "INFORMATION_SCHEMA"
SHOW TABLES;

-- MOSTRA AS CONFIGURAÇÕES E A VERSÃO DO BANCO DE DADOS
STATUS;

-- MOSTRA UMA DESCRIÇÃO DA TABELA
DESCRIBE TABLES;

-- MOSTRA AS COLUNAS DE "TABLES"
SHOW COLUMNS FROM TABLES;

SELECT * FROM TABLES;

-- MOSTRA AS TABELAS DO AULALAB
SELECT * FROM TABLES WHERE TABLE_SCHEMA = "AULALAB";

-- MOSTRA O NOME DA COLUNA DE TODAS AS COLUNAS DO BANCO DE DADOS
SELECT COLUMN_NAME FROM COLUMNS;

DESCRIBE COLUMNS;

-- MOSTRA AS COLUNAS DA TABELA OU VISÃO "COLUMNS"
SHOW COLUMNS FROM COLUMNS;

-- EXIBE AS COLUNAS DO DATABASE SCHEMA "AULALAB"
SELECT * FROM COLUMNS WHERE TABLE_SCHEMA = "AULALAB";

-- MOSTRA TODAS AS TABELAS QUE TEM CONSTRAINT NO NOME
-- OBS.: O % TEM O VALOR DE "QUALQUER COISA", OU SEJA, INDEPENDENTE DOS CARACTERES QUE TIVER ANTES OU DEPOIS DA PALAVRA CONSTRAINT, ELE VAI TRAZER
SELECT TABLE_NAME FROM TABLES WHERE TABLE_NAME LIKE "%CONSTRAINT%";

SELECT * FROM TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = "AULALAB";

SELECT * FROM REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = "AULALAB";

SHOW COLUMNS FROM REFERENTIAL_CONSTRAINTS;
DESCRIBE REFERENTIAL_CONSTRAINTS;

SHOW COLUMNS FROM ROUTINES;

SELECT * FROM ROUTINES WHERE ROUTINE_SCHEMA = "AULALAB";

-- RECUPERA O CÓDIGO FONTE DA STORED PROCEDURE
SELECT ROUTINE_DEFINITION FROM ROUTINES WHERE ROUTINE_NAME = "ELEVAR_AO_QUADRADO";

SELECT SITE_NOME, COUNT (*) AS QTDE
FROM EQUIPAMENTO E
GROUP BY SITE_NOME
ORDER BY 2 DESC;