/*23/02/2024*/

-- CENÁRIO EMPRESA DE TELECOM

-- CRIAR A TABELA SITE
CREATE TABLE SITE (
	SITE_NOME VARCHAR (30) NOT NULL,
	TIPO VARCHAR (30),
	ENDERECO VARCHAR (50),
	PRIMARY KEY(SITE_NOME)
);

-- CRIAR A TABELA EQUIPAMENTO
CREATE TABLE EQUIPAMENTO (
	SITE_NOME VARCHAR (30) NOT NULL,
	EQUIP_NOME VARCHAR (30) NOT NULL,
	TIPO VARCHAR (30),
	MODELO VARCHAR (30),
	FABRICANTE VARCHAR (30),
	PRIMARY KEY (EQUIP_NOME, SITE_NOME)
);

-- DEFINE A CHAVE ESTRANGEIRA "SITE_NOME" COMO FOREIGN KEY (CHAVE ESTRANGEIRA) DA TABELA EQUIPAMENTO, CHAVE ESSA QUE FAZ REFERÊNCIA AO ATRIBUTO "SITE_NOME" DA TABELA SITE
ALTER TABLE EQUIPAMENTO ADD FOREIGN KEY (SITE_NOME) REFERENCES SITE (SITE_NOME);

-- INSERE DADOS NA TABELA SITE
INSERT INTO SITE (SITE_NOME, TIPO, ENDERECO) VALUES ('FRC_CE', 'CENTRAL', 'RUA DAS FLORES');

-- INSERE DADOS NA TABELA SITE
INSERT INTO SITE (SITE_NOME, TIPO, ENDERECO) VALUES ('FRC_ES', 'CENTRAL', 'RUA DAS ROSAS');

-- INSERE DADOS NA TABELA SITE
INSERT INTO SITE (SITE_NOME, TIPO, ENDERECO) VALUES ('FRC_SS', 'CENTRAL', 'RUA DAS ORQUIDEAS');

-- INSERE DADOS NA TABELA SITE
INSERT INTO SITE (SITE_NOME, TIPO, ENDERECO) VALUES ('FRC_LP', 'CENTRAL', 'RUA DAS CASAS');

-- INSERE DADOS NA TABELA SITE
INSERT INTO SITE (SITE_NOME, TIPO, ENDERECO) VALUES ('FRC_JI', 'CENTRAL', 'RUA DOS PREDIOS');

-- INSERE DADOS NA TABELA SITE
INSERT INTO SITE (SITE_NOME, TIPO, ENDERECO) VALUES ('FRC_PN', 'CENTRAL', 'RUA DOS PROCESSADORES');

-- INSERE DADOS NA TABELA SITE
INSERT INTO SITE (SITE_NOME, TIPO, ENDERECO) VALUES ('FRC_JL', 'CENTRAL', 'RUA DOS TECLADOS');

-- VERIFICAR AS CONSTRAINTS EXISTENTES NO BANCO DE DADOS "AULALAB"
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'AULALAB';

-- INSERE DADOS NA TABELA EQUIPAMENTO
INSERT INTO EQUIPAMENTO (SITE_NOME, EQUIP_NOME, TIPO, MODELO, FABRICANTE) VALUES 
('FRC_CE', 'FRC_CE_OLT01', 'OLT', 'MA5800', 'HUAWEI'),
('FRC_ES', 'FRC_ES_OLT01', 'OLT', '7360', 'NOKIA'),
('FRC_JI', 'FRC_JI_OLT01', 'OLT', 'MA5800', 'HUAWEI');

-- NÃO ATUALIZA O DADO, POIS JÁ EXISTE UMA CHAVE PRIMÁRIA COM O MESMO DADO "FRC_ES" QUE JÁ ESTÁ SENDO INSERIDO, NÃO É EXECUTADO PARA MANTER A INTEGRIDADE DO BANCO DE DADOS
UPDATE SITE
	SET SITE_NOME = 'FRC_ES'
	WHERE SITE_NOME = 'FRC_JL';

-- NÃO ATUALIZA O DADO, POIS O DADO "FRC_CE" ESTÁ VINCULADO À UM DADO DA TABELA EQUIPAMENTO, ELE É CHAVE ESTRANGEIRA DE UM DADO DA TABELA EQUIPAMENTO, NÃO É EXECUTADO PARA MANTER A INTEGRIDADE DO BANCO DE DADOS
UPDATE SITE
	SET SITE_NOME = 'FRC_JP'
	WHERE SITE_NOME = 'FRC_CE';
	
-- NÃO EXCLUI O DADO, POIS O DADO "FRC_JI" É UMA CHAVE ESTRANGEIRA NA TABELA EQUIPAMENTO, NÃO É EXECUTADO PARA MANTER A INTEGRIDADE DO BANCO DE DADOS
DELETE FROM SITE WHERE SITE_NOME = 'FRC_JI';

-- EXCLUI O DADO, POIS NÃO TEM NENHUM DADO DE OSUTRA TABELA VINCULADO À ELE, ELE NÃO É CHAVE ESTRANGEIRA EM OUTRA TABELA
DELETE FROM SITE WHERE SITE_NOME = 'FRC_PN';