/*03/05/2024*/

/**TAREFA**/
CREATE TABLE PORTA (
    NUMERO INT NOT NULL,
    VELOCIDADE VARCHAR(10),
    EQUIPAMENTO_NOME VARCHAR(30) NOT NULL,	
    SITE_NOME VARCHAR(30) NOT NULL,
    SLOT_TIPO VARCHAR(30),
	PRIMARY KEY (NUMERO, EQUIPAMENTO_NOME, SITE_NOME)
);

ALTER TABLE PORTA ADD FOREIGN KEY (EQUIPAMENTO_NOME) REFERENCES EQUIPAMENTO (EQUIPAMENTO_NOME);

ALTER TABLE PORTA ADD FOREIGN KEY (SITE_NOME) REFERENCES SITE (SITE_NOME);

DELIMITER $$

CREATE PROCEDURE PRC_CARGA_PORTA(OUT P_QTDE DECIMAL)
BEGIN
    DECLARE V_QTDE DECIMAL DEFAULT 0;
    DECLARE EQUIPAMENTO_NOME_VAL VARCHAR(30);
    DECLARE SITE_NOME_VAL VARCHAR(30);
    DECLARE PORTA_COUNT INT;
    DECLARE PORTA_NUMERO INT;

    DECLARE CURS1 CURSOR FOR
        SELECT EQUIPAMENTO_NOME, SITE_NOME
        FROM EQUIPAMENTO;

    OPEN CURS1;

    READ_CURSOR: LOOP
        FETCH CURS1 INTO EQUIPAMENTO_NOME_VAL, SITE_NOME_VAL;

        SELECT COUNT(*) INTO PORTA_COUNT
        FROM PORTA
        WHERE EQUIPAMENTO_NOME = EQUIPAMENTO_NOME_VAL
        AND SITE_NOME = SITE_NOME_VAL;

        
        SET PORTA_NUMERO = PORTA_COUNT + 1;
        WHILE PORTA_NUMERO <= 638 DO
            
            IF NOT EXISTS (
                SELECT 1 FROM PORTA
                WHERE EQUIPAMENTO_NOME = EQUIPAMENTO_NOME_VAL
                AND SITE_NOME = SITE_NOME_VAL
                AND NUMERO = PORTA_NUMERO
            ) THEN
                
                INSERT INTO PORTA (NUMERO, VELOCIDADE, EQUIPAMENTO_NOME, SITE_NOME, SLOT_TIPO)
                VALUES (PORTA_NUMERO, CASE WHEN PORTA_NUMERO <= PORTA_COUNT + 90 THEN '10M' ELSE '1GB' END, EQUIPAMENTO_NOME_VAL, SITE_NOME_VAL, CASE WHEN PORTA_NUMERO <= PORTA_COUNT + 90 THEN 'LINE' ELSE 'LINK' END);
                SET V_QTDE = V_QTDE + 1;
            END IF;
            SET PORTA_NUMERO = PORTA_NUMERO + 1;
        END WHILE;
    END LOOP READ_CURSOR;

    CLOSE CURS1;

    SET P_QTDE = V_QTDE; 
END$$

DELIMITER ;


CALL PRC_CARGA_PORTA(@P_QTDE);

SELECT COUNT(*) FROM PORTA;

SELECT COUNT(*) FROM PORTA WHERE EQUIPAMENTO_NOME = 'FRC_SS_OLT_01' AND SLOT_TIPO = 'LINE';

SELECT COUNT(*) FROM PORTA WHERE EQUIPAMENTO_NOME = 'FRC_SS_OLT_01' AND SLOT_TIPO = 'LINK';

SELECT COUNT(*) FROM PORTA WHERE EQUIPAMENTO_NOME = 'FRC_SS_OLT_02' AND SLOT_TIPO = 'CONTROLADORA';

/**AULA**/
CREATE FUNCTION FNC_BUSC ()
RETURNS DECIMAL 
BEGIN


END

SELECT NOME,
	(SALARIO * ALIQUOTA) - DEDUCAO AS IMPOSTO_RENDA
	SALARIO - ((SALARIO * ALIQUOTA) - DEDUCAO)) AS SALARIO_LIQUIDO
 FROM FUNCIONARIO;
 
 
 CREATE TABLE IMPOSTO_RENDA(
	FAIXA_INI DECIMAL (7, 2),
	FAIXA_FIM DECIMAL (7,2),
	ALIQUOTA DECIMAL (3, 1),
	DEDUCAO DECIMAL (7, 2)
 );
 
INSERT INTO IMPOSTO_RENDA (FAIXA_INI, FAIXA_FIM, ALIQUOTA, DEDUCAO) VALUES (0, 2258, 0, 0);
INSERT INTO IMPOSTO_RENDA (FAIXA_INI, FAIXA_FIM, ALIQUOTA, DEDUCAO) VALUES (2259, 2826, 7.5 , 169);
INSERT INTO IMPOSTO_RENDA (FAIXA_INI, FAIXA_FIM, ALIQUOTA, DEDUCAO) VALUES (2827, 3751, 15, 381);
INSERT INTO IMPOSTO_RENDA (FAIXA_INI, FAIXA_FIM, ALIQUOTA, DEDUCAO) VALUES (3752, 4664, 22.5, 662);
INSERT INTO IMPOSTO_RENDA (FAIXA_INI, FAIXA_FIM, ALIQUOTA, DEDUCAO) VALUES (4665, 99999, 27.5, 896);

DELIMITER $$

CREATE FUNCTION FNC_CALC_IMPOSTO(P_SALARIO DECIMAL) 
RETURNS DECIMAL(7, 2)
BEGIN
    DECLARE P_IMPOSTO DECIMAL(7, 2);

    SELECT (P_SALARIO * IR.ALIQUOTA / 100) - IR.DEDUCAO
        INTO P_IMPOSTO
        FROM IMPOSTO_RENDA IR
        WHERE P_SALARIO BETWEEN IR.FAIXA_INI AND IR.FAIXA_FIM;

    RETURN P_IMPOSTO;
END$$

DELIMITER ;

SELECT PNOME, SALARIO AS SALARIO_ANUAL, SALARIO/12 AS SALARIO_MENSAL, FNC_CALC_IMPOSTO(SALARIO/12) AS IMPOSTO_RENDA, SALARIO/12-FNC_CALC_IMPOSTO(SALARIO/12) AS SALARIO_LIQUIDO 
	FROM FUNCIONARIO;
	