/*16/02/2024*/

-- CRIA O BANCO DE DADOS
CREATE DATABASE AULALAB;

-- SELECIONA O BANCO DE DADOS
USE AULALAB;

-- MOSTRA OS BANCO DE DADOS EXISTENTES
SHOW DATABASES;

-- APAGA A TABELA CLIENTE
DROP TABLE CLIENTE;

-- APAGA O BANCO DE DADOS AULALAB
DROP DATABASE AULALAB;

-- CRIA UMA TABELA (OBS.: O ATRIBUTO CPF FOI ESCOLHIDO PELO TIPO VARCHAR, POIS EXISTE CPFS QUE INICIAM COM 0 E O ATRIBUTO NUMÉRICO NÃO CONSIDERA 0 À ESQUERDA)
CREATE TABLE CLIENTE (
	CPF VARCHAR(11) NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	ENDERECO VARCHAR(30),
	NUMERO INT(5),
	SEXO VARCHAR(1),
	DATA_NASCIMENTO DATE
);

-- MOSTRA AS TABELAS EXISTENTES NO BANCO DE DADOS
SHOW TABLES;

-- MOSTRA OS DADOS PRESENTES NA TABELA
SELECT * FROM CLIENTE;

-- MOSTRA O SCRIPT DE CRIAÇÃO DA TABELA
SHOW CREATE TABLE CLIENTE;

-- MOSTRA UMA DESCRIÇÃO DA TABELA
DESC CLIENTE;

-- INSERE REGISTROS NA TABELA
INSERT INTO CLIENTE (CPF, NOME, ENDERECO, NUMERO, SEXO, DATA_NASCIMENTO) VALUES ('12345678901', 'JOSÉ', 'RUA DAS FLORES', 123, 'M', '1975-03-21');

-- INSERE REGISTROS NA TABELA
INSERT INTO CLIENTE (CPF, NOME, ENDERECO, NUMERO, SEXO, DATA_NASCIMENTO) VALUES ('98765432101', 'MARIA', 'RUA DAS ROSAS', 1236, 'F', '1990-01-10');

-- TRANSFORMA O ATRIBUTO CPF DA TABELA CLIENTE EM CHAVE PRIMÁRIA
ALTER TABLE CLIENTE MODIFY CPF VARCHAR(11) PRIMARY KEY;

-- ATUALIZA TODOS OS REGISTRO DA TABELA
UPDATE CLIENTE SET CPF = '14725836923'; -- IRÁ ATUALIZAR TODOS OS CPFS DA TABELA, POIS ESTÁ EM A CLÁUSULA DE SELEÇÃO "WHERE"

-- ATUALIZA UM ÚNICO REGISTRO DA TABELA
UPDATE CLIENTE SET CPF = '14725836923' WHERE CPF = '12345678901'; -- IRÁ ATUALIZAR TODOS OS CPFS DA TABELA, POIS ESTÁ EM A CLÁUSULA DE SELEÇÃO "WHERE"

-- CRIA UMA TABELA (OBS.: O ATRIBUTO CPF FOI ESCOLHIDO PELO TIPO VARCHAR, POIS EXISTE CPFS QUE INICIAM COM 0 E O ATRIBUTO NUMÉRICO NÃO CONSIDERA 0 À ESQUERDA)
CREATE TABLE DEPENDENTE (
	CPF_CLIENTE VARCHAR(11) NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	SEXO VARCHAR(1),
	DATA_NASCIMENTO DATE,
	PRIMARY KEY (CPF_CLIENTE, NOME)
);

-- DEFINE A CHAVE ESTRANGEIRA "CPF_CLIENTE" COMO FOREIGN KEY (CHAVE ESTRANGEIRA) DA TABELA DEPENDENTE, CHAVE ESSA QUE FAZ REFERÊNCIA AO ATRIBUTO "CPF" DA TABELA CLIENTE
ALTER TABLE DEPENDENTE ADD FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE (CPF);

-- INSERE REGISTROS NA TABELA
INSERT INTO DEPENDENTE (CPF_CLIENTE, NOME, SEXO, DATA_NASCIMENTO) VALUES ('12345678901', 'MÁRIO', 'M', '2000-03-21');

-- INSERE REGISTROS NA TABELA
INSERT INTO DEPENDENTE (CPF_CLIENTE, NOME, SEXO, DATA_NASCIMENTO) VALUES ('12345678901', 'MARCIO', 'M', '2010-01-30');

-- INSERE REGISTROS NA TABELA (OBS.: NÃO DEIXA REALIZAR A INSERÇÃO, POIS NÃO TEM NENHUM REGISTRO NA TABELA CLIENTE COM ESSE CPF, OU SEJA, ESSA INSERÇÃO NA TABELA DEPENDENTE SERIA UM REGISTRO FILHO DA TABELA CLIENTE, PORÉM ESSE CPF NÃO EXISTE NA TABELA CLIENTE)
INSERT INTO DEPENDENTE (CPF_CLIENTE, NOME, SEXO, DATA_NASCIMENTO) VALUES ('12345678922', 'MARCIO', 'M', '2010-01-30');

-- INSERE REGISTROS NA TABELA
INSERT INTO DEPENDENTE (CPF_CLIENTE, NOME, SEXO, DATA_NASCIMENTO) VALUES ('98765432101', 'CLAUDINEI', 'M', '2020-01-01');

-- APAGA UM ÚNICO REGISTRO DA TABELA
DELETE FROM DEPENDENTE WHERE CPF_CLIENTE = '12345678901';

-- APAGA UM ÚNICO REGISTRO DA TABELA (OBS.: COMO ESSE REGISTRO DA TABELA CLIENTE ESTÁ VINCULADO A DADOS DA TABELA DEPENDENTE, NÃO É POSSÍVEL REALIZAR A EXCLUSÃO, OU SEJA, ELE É UM REGISTRO PAI DE UM REGISTRO DA TABELA DEPENDENTE)
DELETE FROM CLIENTE WHERE CPF = '12345678901';

-- APAGA TODOS OS REGISTROS DA TABELA CLIENTE E TODOS OS REGISTROS DE OUTRAS TABELAS QUE ESTEJAM VINCULADOS AOS REGISTROS DA TABELA CLIENTE (OBS.: NÃO É RECOMENDADO UTILIZAR)
DELETE FROM CLIENTE CASACADE;

-- COMANDOS DE DDL UTILIZADOS NESSA AULA (CREATE, ALTER, DROP, SHOW)
-- COMANDOS DE DML UTILIZADOS NESSA AULA (SELECT, INSERT, DELETE, UPDATE)