/*22/03/2024*/

/**TAREFA**/
-- QUANTIDADE DE COLUNAS POR TABELA DO ESQUEMA "AULALAB"
SELECT TABLE_NAME, COUNT(*) AS QTD_COLUNAS
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'AULALAB'
GROUP BY TABLE_NAME;

-- QUANTIDADE DE CONSTRAINTS DE CHECK POR ESQUEMA
SELECT TABLE_SCHEMA, COUNT(*) AS QTD_CHECK
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'CHECK'
GROUP BY TABLE_SCHEMA;

-- O MYSQL 5.5 NÃO ACEITA O USO DE CHECK CONSTRAINTS, POR ISSO O COMANDO ANTERIOR RETORNA VAZIO. UMA ALTERNATIVA FOI UTILIZAR AS TRIGGERS
SELECT TRIGGER_SCHEMA, COUNT(*) AS QTD_TRIGGERS
FROM INFORMATION_SCHEMA.TRIGGERS
GROUP BY TRIGGER_SCHEMA;

-- QUANTIDADE DE REFERENTIAL POR ESQUEMA
SELECT TABLE_SCHEMA, COUNT(*) AS QTD_FK
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
GROUP BY TABLE_SCHEMA;

/***CORREÇÃO***/
-- QUANTIDADE DE TABELAS POR ESQUEMA
SELECT T.TABLE_SCHEMA, COUNT(*) AS QTDE	
	FROM TABLES AS TABELA
	GROUP BY T.TABLE_SCHEMA;
	
-- QUANTIDADE DE COLUNAS POR ESQUEMA
SELECT C.TABLE_SCHEMA, COUNT(*) AS QTDE
	FROM COLUMNS AS CACHE_INSTANCES
	GROUP BY C.TABLE_SCHEMA;
	
-- QUANTIDADE DE COLUNAS POR TABELA DO ESQUEMA "AULALAB"
SELECT C.TABLE_NAME, COUNT(*) AS QTDE	
	FROM COLUMNS AS C
	WHERE C.TABLE_SCHEMA = "AULALAB";
	GROUP BY C.TABLE_NAME
	ORDER BY COUNT(*) DESC;
	
	
-- QUANTIDADE DE CONSTRAINTS DE CHECK E REFERENTIAL POR ESQUEMA
SELECT R.CONSTRAINT_SCHEMA, COUNT(*) AS QTDE
	FROM REFERENTIAL_CONSTRAINTS AS R
	GROUP BY R.CONSTRAINT_SCHEMA
	ORDER BY 2 ASC;

-- COMO VER O TEXTO DE UMA ROTINA
SELECT R.ROUTINE_DEFINITION
	FROM ROUTINES R;
	
-- COMO VER OS DISTINTOS TIPOS DE ROUTINA
SELECT DISTINCT R.ROUTINE_TYPE
	FROM ROUTINES R;
	
/**AULA**/
-- CRIO UMA VARIÁVEL "ROWNUM", ATRIBUO A ELA O VALOR 0 E DEFINO O FIM DELA PARA 10 ITERAÇÕES. ELA RODA 10 VEZES O NÚMERO 0 DENTRO DA TABELA EQUIPAMENTO
-- := ATRIBUI VALOR
-- = TESTA O VALOR
-- PASSO 1
SELECT @ROWNUM:=0 FROM EQUIPAMENTO LIMIT 10;

-- PASSO 2
-- CONCEITO DE SUBQUERY, EXECUTA PRIMEIRO O QUE ESTÁ DENTRO DOS PARENTESES 
SELECT @ROWNUM:= @ROWNUM + 1 AS SLOT FROM
	(SELECT @ROWNUM:=0 FROM EQUIPAMENTO LIMIT 10) AS RESULTADO;

-- PASSO 3
SELECT SLOT, 
	CASE WHEN SLOT = '8' THEN 'CONTROLADORA'
	WHEN SLOT IN ('9','10') THEN 'LINK'
	ELSE 'LINE' END AS SLOT_TIPO
	FROM (SELECT @ROWNUM := @ROWNUM + 1 AS SLOT FROM (SELECT @ROWNUM := 0 FROM EQUIPAMENTO LIMIT 10) 
	AS RESULTADO) AS PLACA;

-- PASSO 4
SELECT SITE_NOME, EQUIPAMENTO_NOME
	FROM EQUIPAMENTO;
	
-- PASSO 5
SELECT B.EQUIPAMENTO_NOME, B.SITE_NOME, A.SLOT, A.SLOT_TIPO
	FROM (SELECT SLOT, 
	CASE WHEN SLOT = '8' THEN 'CONTROLADORA'
	WHEN SLOT IN ('9','10') THEN 'LINK'
	ELSE 'LINE' END AS SLOT_TIPO
	FROM (SELECT @ROWNUM := @ROWNUM + 1 AS SLOT FROM (SELECT @ROWNUM := 0 FROM EQUIPAMENTO LIMIT
	10) AS RESULTADO) AS PLACA) AS A,
	(SELECT EQUIPAMENTO_NOME, SITE_NOME FROM EQUIPAMENTO) AS B
	ORDER BY B.SITE_NOME, B.EQUIPAMENTO_NOME, A.SLOT;
	
-- PASSO 6
INSERT INTO PLACA 
		(SITE_NOME, EQUIPAMENTO_NOME, SLOT, SLOT_TIPO) VALUES
			('FRC_CE','FRC_CE_SWC_01','1','LINE');
			
-- PASSO 7
DELETE FROM PLACA;

-- PASSO 8 
SELECT CONCAT ('INSERT INTO PLACA (SLOT, EQUIPAMENTO_NOME, SITE_NOME, SLOT_TIPO) VALUES (''', D.SLOT, ''',''', 
D.EQUIPAMENTO_NOME, ''',''', D.SITE_NOME, ''',''', D.SLOT_TIPO,''');')
FROM (SELECT A.SLOT, B.EQUIPAMENTO_NOME, B.SITE_NOME, A.SLOT_TIPO
FROM (SELECT SLOT, 
CASE WHEN SLOT = '8' THEN 'CONTROLADORA'
WHEN SLOT IN ('9','10') THEN 'LINK'
ELSE 'LINE' END AS SLOT_TIPO
FROM (SELECT @ROWNUM := @ROWNUM + 1 AS SLOT FROM (SELECT @ROWNUM := 0 FROM EQUIPAMENTO
LIMIT 10) AS RESULTADO) AS PLACA) AS A,
(SELECT EQUIPAMENTO_NOME, SITE_NOME FROM EQUIPAMENTO) AS B
ORDER BY B.SITE_NOME, B.EQUIPAMENTO_NOME, A.SLOT) AS D;
