/*26/04/2024*/

-- CORREÇÃO PROCEDURE PRC_CARGA_PLACA

-- OPERAÇÃO DE JUNÇÃO
SELECT *
FROM
  (SELECT *
   FROM
     (SELECT D.DNOME, F.PNOME, F.UNOME 
      FROM DEPARTAMENTO D, FUNCIONARIO F
      WHERE D.CPF_GERENTE = F.CPF) AS DEP_GER
  ) AS RESULTADO;
		
SELECT D.DNOME, F.PNOME, F.UNOME
FROM DEPARTAMENTO D
INNER JOIN FUNCIONARIO F ON D.CPF_GERENTE = F.CPF;
	
-- OPERAÇÃO DE DIVISÃO
SELECT CPFS_PNRS.FCPF
FROM 
  (SELECT T.PNR	
   FROM
     (SELECT *
      FROM FUNCIONARIO F
      WHERE F.PNOME = 'JOAO' AND F.UNOME = 'SILVA') AS SILVA, TRABALHA_EM T
   WHERE SILVA.CPF = T.FCPF) AS SILVA_PNRS,
  (SELECT * 
   FROM
     (SELECT T.FCPF, T.PNR
      FROM TRABALHA_EM T) AS CPF_PNRS) AS CPFS_PNRS
WHERE SILVA_PNRS.PNR = CPFS_PNRS.PNR
GROUP BY CPFS_PNRS.FCPF
HAVING COUNT(CPFS_PNRS.PNR) >= COUNT(SILVA_PNRS.PNR);