/*19/04/2024*/

/**TAREFA**/
DELIMITER $$
CREATE PROCEDURE PRC_CARGA_PLACA(OUT P_QTDE DECIMAL)
BEGIN
    DECLARE V_QTDE DECIMAL DEFAULT 0;
    DECLARE SLOT_VAL VARCHAR(2);
    DECLARE EQUIPAMENTO_NOME_VAL VARCHAR(30);
    DECLARE SITE_NOME_VAL VARCHAR(30);
    DECLARE SLOT_TIPO_VAL VARCHAR(30);

    DECLARE CURS1 CURSOR FOR
        SELECT A.SLOT, B.EQUIPAMENTO_NOME, B.SITE_NOME, A.SLOT_TIPO
        FROM (
            SELECT SLOT, 
                CASE 
                    WHEN SLOT = '8' THEN 'CONTROLADORA'
                    WHEN SLOT IN ('9','10') THEN 'LINK'
                    ELSE 'LINE' 
                END AS SLOT_TIPO
            FROM (
                SELECT @ROWNUM := @ROWNUM + 1 AS SLOT 
                FROM (SELECT @ROWNUM := 0 FROM EQUIPAMENTO LIMIT 10) AS RESULTADO
            ) AS PLACA
        ) AS A,
        (SELECT EQUIPAMENTO_NOME, SITE_NOME FROM EQUIPAMENTO) AS B;

    OPEN CURS1;
    READ_CURSOR: LOOP
        FETCH CURS1 INTO SLOT_VAL, EQUIPAMENTO_NOME_VAL, SITE_NOME_VAL, SLOT_TIPO_VAL;
        
        INSERT INTO PLACA (SLOT, EQUIPAMENTO_NOME, SITE_NOME, SLOT_TIPO) 
        VALUES (SLOT_VAL, EQUIPAMENTO_NOME_VAL, SITE_NOME_VAL, SLOT_TIPO_VAL);
        
        SET V_QTDE = V_QTDE + 1;
    END LOOP READ_CURSOR;
    
    SET P_QTDE = V_QTDE;
    
    CLOSE CURS1;
END$$
DELIMITER ;

CALL PRC_CARGA_PLACA(@P_QTDE);

/**AULA**/
-- OPERAÇÃO DE SUBTRAÇÃO
SELECT CPF
FROM FUNCIONARIO
WHERE CPF NOT IN (SELECT FCPF FROM DEPENDENTE);

SELECT * FROM FUNCIONARIO 
	WHERE DNR = 5 AND CPF NOT IN (SELECT FCPF FROM TRABALHA_EM WHERE DNR = 10);

SELECT F.PNOME, F.UNOME
	FROM FUNCIONARIO F
LEFT JOIN DEPENDENTE D ON D.FCPF AND D.FCPF IS NULL;

SELECT * FROM FUNCIONARIO F WHERE NOT EXISTS (SELECT 1 FROM DEPENDENTE D WHERE D.FCPF = F.CPF);

-- PRODUTO CARTESIANO

SELECT PNOME, UNOME, NOME_DEPENDENTE 
FROM
(SELECT * 
FROM 
(SELECT * 
FROM (SELECT PNOME, UNOME, CPF 
	FROM
	(SELECT * FROM FUNCIONARIO F WHERE F.SEXO = 'F') AS FUNC_MULHERES) AS FUNC_NOMES, DEPENDENTE D) AS FUNC_DEPENDENTE WHERE CPF=FCPF) AS DEPENDENTE_PARTIC;