/*24/05/2024*/

--1) 
SELECT 
    P.PROJNOME AS PROJETO_NOME, AVG(CAST((SELECT SALARIO FROM FUNCIONARIO WHERE CPF = T.FCPF) AS DECIMAL(7,2))) AS SAL_MEDIO
FROM 
    TRABALHA_EM T
JOIN 
    PROJETO P ON T.PNR = P.PROJNUMERO
GROUP BY 
    P.PROJNOME;
	
--2)
SELECT 
    MIN(HORAS) AS MENOR_QTD_HORAS,
    MAX(HORAS) AS MAIOR_QTD_HORAS,
    AVG(HORAS) AS MEDIA_QTD_HORAS,
    SUM(HORAS) AS TOTAL_HORAS
FROM 
    TRABALHA_EM;

--3)
DELIMITER $$

CREATE FUNCTION MULT(NUM1 DECIMAL(7,2), NUM2 DECIMAL(7,2))
RETURNS DECIMAL(7,2)
BEGIN
    DECLARE RESULTADO DECIMAL(7,2);
    SET RESULTADO = NUM1 * NUM2;
    RETURN RESULTADO;
END$$

DELIMITER ;

SELECT MULT(5, 7) AS RESULTADO;

--4)
DELIMITER $$

CREATE PROCEDURE ATUALIZAR_SAL()
BEGIN
    UPDATE FUNCIONARIO
    SET SALARIO = CAST(SALARIO AS DECIMAL(7,2)) * CASE 
                    WHEN DNR = 1 THEN 1.10 -- MATRIZ: AUMENTO DE 10%
                    WHEN DNR = 4 THEN 1.40 -- ADMINISTRAÇÃO: AUMENTO DE 40%
                    WHEN DNR = 5 THEN 1.50 -- PESQUISA: AUMENTO DE 50%
                 END;
END$$

DELIMITER ;

CALL ATUALIZAR_SAL();

--5)
SELECT * FROM (SELECT PNOME, UNOME, SALARIO
	FROM (SELECT * FROM FUNCIONARIO 
	WHERE DNR = 5) AS FUNCS_DEPT5) AS RESULTADO; 
	
--6)
SELECT * 
FROM
(SELECT PNOME, UNOME, NOME_DEPENDENTE 
FROM
(SELECT * 
FROM 
(SELECT * 
FROM (SELECT PNOME, UNOME, CPF 
	FROM
	(SELECT * FROM FUNCIONARIO F WHERE F.SEXO = 'F') AS FUNC_MULHERES) AS FUNCNOMES, DEPENDENTE D) AS FUNC_DEPENDENTES WHERE CPF=FCPF) AS DEPENDENTE_PARTIC) AS RESULTADO;

